# Base Configuration
# Create your own profiles using this base
# You can make it Coding, Gaming, Work etc.
# Use LoadConf["name.conf"] to load the config using a shortcut.

Allow_Bad_Keys=Disabled
Virtual_Desktop_Switch=Disbaled
New_Desktop_Creation=Disabled
Auto_Remove_Virtual_Desktop=Disbaled
Window_And_Virtual_Desktop_Switch=Disabled
Transparency = Disabled
StealFocus = Disabled
DarkModeTitleBar = Disabled
SystemBackdrop = 2